spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: admin
    password: Burns125
    url: jdbc:oracle:thin:@database-1.clv5gcglsrgr.us-east-1.rds.amazonaws.com:1521:ORCL
  mail:
    host: smtp.gmail.com
    port: 587
    username: CJPJavaMail@gmail.com
    password: Orioles123
    properties: 
     mail: 
      smtp: 
        auth: true
        startls:
          enable: true
    
server:
  port: 8090
  
    
